# Generated by Django 2.1.5 on 2019-07-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=30, unique=True)),
                ('u_email', models.CharField(max_length=30, unique=True)),
                ('passwd', models.CharField(max_length=16)),
                ('UUID', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
