# Generated by Django 2.1.5 on 2019-07-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190707_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['user_ID'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
