# Generated by Django 2.1.5 on 2019-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190707_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailycheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernum', models.IntegerField(max_length=6)),
                ('date', models.DateTimeField(max_length=10)),
                ('timeon', models.CharField(max_length=10)),
                ('timeoff', models.CharField(max_length=10)),
                ('leave', models.BooleanField(choices=[(0, '否'), (1, '是')], max_length=1)),
            ],
            options={
                'verbose_name': '上班记录',
                'verbose_name_plural': '上班记录',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('usernum', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('IMEI', models.IntegerField(max_length=16, unique=True)),
                ('telenum', models.IntegerField(blank=True, max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='img')),
                ('sex', models.BooleanField(blank=True, choices=[(0, '男'), (1, '女')], max_length=1)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('pronum', models.IntegerField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernum', models.IntegerField(max_length=6)),
                ('date', models.DateTimeField(max_length=10)),
                ('timeoff', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '加班记录',
                'verbose_name_plural': '加班记录',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernum', models.IntegerField(max_length=6)),
                ('date', models.DateTimeField(max_length=10)),
                ('timeon', models.CharField(max_length=10)),
                ('timeoff', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '请假记录',
                'verbose_name_plural': '请假记录',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='out_buss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernum', models.IntegerField(max_length=6)),
                ('dateon', models.DateTimeField(max_length=10)),
                ('dateoff', models.DateTimeField(max_length=10)),
            ],
            options={
                'verbose_name': '出差记录',
                'verbose_name_plural': '出差记录',
                'ordering': ['usernum'],
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronum', models.IntegerField(max_length=20, unique=True)),
                ('usernum', models.IntegerField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('timeon', models.CharField(max_length=10)),
                ('timeoff', models.CharField(max_length=10)),
                ('ps', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['pronum'],
            },
        ),
        migrations.CreateModel(
            name='Reg_mesg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_email', models.CharField(max_length=30, unique=True)),
                ('r_vcode', models.CharField(max_length=5)),
                ('r_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '注册',
                'verbose_name_plural': '注册',
                'ordering': ['r_email'],
            },
        ),
    ]
