# Generated by Django 2.1.5 on 2019-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_dailycheck_employee_extra_leave_out_buss_project_reg_mesg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pronum',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telenum',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
